version: '3.8'

services:
  frontend:
    build: 
      context: ./ecommerce-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"   # Vite default port
    volumes:
      - ./ecommerce-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["pnpm", "dev"]

  backend:
    build: 
      context: ./ecommerce-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"   # Your backend port
    volumes:
      - ./ecommerce-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/ecommerce
    command: ["pnpm", "start:dev"]
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
